# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: ultralytics_yolo_example
description: "Demonstrates how to use the ultralytics_yolo plugin."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1
  flutter: ">=3.32.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.1.2
  path_provider: ^2.0.0
  archive: ^4.0.7
  http: ^1.2.1
  go_router: ^16.0.0
  provider: ^6.1.1         # ✅ 추가된 부분
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  cached_network_image: ^3.3.1  # ✅ 최신 버전 또는 안정 버전 명시
  permission_handler: ^11.0.0
  image_gallery_saver:
    path: packages/image_gallery_saver
  

  ultralytics_yolo:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/models/
    - assets/logo.png
    - assets/applogo.png
    - assets/models/dental_best_float32.tflite

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/applogo.png"

flutter_native_splash:
  color: "#ffffff" # 배경색
  image: assets/splash.png # 로고 이미지 경로
  android: true
  ios: true